package game.enums;

public enum DigimonType
{
    ABNORMAL("ミュータント型"),
    AMPHIBIAN("両生類型"),
    ANCIENT_ANIMAL("古代獣型"),
    ANCIENT_DRAGON("古代竜型"),
    ANGEL("天使型"),
    ANKYLOSAUR("鎧竜型"),
    ARCHANGEL("大天使型"),
    ARMOR("防具型"),
    AUTHORITY("能天使型"),
    AVIAN("鳥型"),
    BABY_DRAGON("幼竜型"),
    BAGRA_ARMY("バグラ軍"),
    BEAST("獣型"),
    BEASTKIN("獣人型"),
    BEAST_KNIGHT("獣騎士型"),
    BIRD("ヒナ鳥型"),
    BIRDKIN("鳥人型"),
    BLUE_FLARE("ブルーフレア"),
    BOSS("バンチョー"),
    BULB("球根型"),
    CARNIVOROUS_PLANT("食虫植物型"),
    CHERUB("智天使型"),
    COMPOSITE("合成型"),
    CYBORG("サイボーグ型"),
    DARK_ANIMAL("魔獸型"),
    DARK_DRAGON("魔竜型"),
    DEMON("鬼人型"),
    DEMON_LORD("魔王型"),
    DINOSAUR("恐竜型"),
    DRAGONKIN("竜人型"),
    D_BRIGADE("D・ブリガード"),
    EARTH_DRAGON("地竜型"),
    EVIL("小恶魔型"),
    EVIL_DRAGON("邪竜型"),
    FAIRY("妖精型"),
    FALLEN_ANGEL("堕天使型"),
    FIRE_DRAGON("火炎竜型"),
    FLAME("火炎型"),
    FOUR_GREAT_DRAGONS("四大竜"),
    GIANT_BIRD("巨鳥型"),
    HOLY_BEAST("聖獣型"),
    HOLY_DRAGON("聖竜型"),
    HOLY_WARRIOR("聖騎士型"),
    ICE_SNOW("氷雪型"),
    INSECTOID("昆虫型"),
    LARVA("幼虫型"),
    LEGEND_ARMS("Legend-Arms"),
    LESSER("レシサー型"),
    LIGHT_DRAGON("光竜型"),
    MACHINE("マシーン型"),
    MACHINE_DRAGON("機竜型"),
    MAGIC_WARRIOR("魔法戦士型"),
    MAMMAL("哺乳類型"),
    MINE("機雷型"),
    MINI_ANGEL("小天使型"),
    MINI_BIRD("小鳥型"),
    MINI_DRAGON("小竜型"),
    MOLLUSK("軟体型"),
    MUTANT("突然変異型"),
    MYTHICAL_BEAST("幻獣型"),
    MYTHICAL_DRAGON("幻竜型"),
    OLYMPOS_XII("オリンポス十二神"),
    PERFECT("パーフェクト型"),
    PUPPET("パペット型"),
    REPTILE("爬虫類型"),
    ROCK("岩型"),
    ROCK_DRAGON("岩竜型"),
    ROYAL_KNIGHT("ロイヤルナイツ"),
    SEA_ANIMAL("水棲哺乳類型"),
    SEA_BEAST("海獣型"),
    SERAPH("熾天使型"),
    SEVEN_GREAT_DEMON_LORDS("七大魔王"),
    SHAMAN("神人型"),
    THREE_GREAT_ANGELS("三大天使"),
    THRONE("座天使型"),
    UNDEAD("アンデッド型"),
    UNIDENTIFIED("不明型"),
    UNIQUE("特異型"),
    VEGETATION("植物型"),
    VIRTUE("力天使型"),
    WARRIOR("戰士型"),
    WEAPON("武器型"),
    WIZARD("魔人型"),
    XROS_HEART("クロスハート"),
    ;
    
    
    final String japanese;
    
    DigimonType(String japanese)
    {
        this.japanese = japanese;
    }
}
