package game.enums;

public enum GameState {
    WAITING,
    INIT,
    SETUP, MULLIGAN,
    START_OF_TURN,
    UNSUSPEND,
    DRAW,
    BREEDING, BREEDING_HATCH, BREEDING_PLAY,
    MAIN,
    PLAY,
    DIGIVOLVE,
    ACTIVATE,
    ATTACK, DECLARE_ATTACK, DECLARE_BLOCKER,
    END_OF_TURN
}
